#!/usr/bin/env node
// Writes apps/web/.env with a port offset so a lane's dev/preview servers
// don't collide with the main checkout's or another lane's.
//
// Usage: NAME=lane-1 OFFSET=100 node scripts/worktree-init.mjs
//   (or: NAME=lane-1 OFFSET=100 make worktree-init)

import { existsSync, writeFileSync } from "node:fs"
import net from "node:net"
import path from "node:path"
import { fileURLToPath } from "node:url"

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const envPath = path.join(repoRoot, "apps/web/.env")

const name = process.env.NAME
if (!name) {
  console.error("Usage: NAME=lane-1 OFFSET=100 make worktree-init")
  process.exit(1)
}

if (existsSync(envPath) && !process.env.FORCE) {
  console.error(`${envPath} already exists — refusing to overwrite (set FORCE=1 to replace).`)
  process.exit(1)
}

function portFree(port) {
  return new Promise((resolve) => {
    const srv = net.createServer()
    srv.once("error", () => resolve(false))
    srv.once("listening", () => srv.close(() => resolve(true)))
    srv.listen(port, "127.0.0.1")
  })
}

async function isOffsetFree(offset) {
  return (await portFree(5173 + offset)) && (await portFree(4173 + offset))
}

let offset = process.env.OFFSET ? Number(process.env.OFFSET) : 100
if (!(await isOffsetFree(offset))) {
  console.warn(`Offset ${offset} has a bound port — probing for the next free multiple of 100.`)
  let candidate = offset
  do {
    candidate += 100
  } while (!(await isOffsetFree(candidate)) && candidate < offset + 1000)
  if (!(await isOffsetFree(candidate))) {
    console.error("No free port offset found in range.")
    process.exit(1)
  }
  offset = candidate
}

const devPort = 5173 + offset
const previewPort = 4173 + offset

writeFileSync(
  envPath,
  `# generated by \`make worktree-init\` — do not edit by hand
WORKTREE_NAME=${name}
PORT_OFFSET=${offset}
VITE_DEV_PORT=${devPort}
VITE_PREVIEW_PORT=${previewPort}
`,
)

console.log(`Wrote ${envPath}`)
console.log(`  dev:     http://localhost:${devPort}`)
console.log(`  preview: http://localhost:${previewPort}`)
